# Generated by Django 3.1.2 on 2020-11-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('phone_number', models.PositiveIntegerField(blank=True, help_text='enter phone number', null=True)),
            ],
        ),
    ]
